
stages:
  - validate
  - plan
  - apply
  - deploy


validate:
  stage: validate
  script:
   - terraform init -reconfigure
   - terraform validate
  tags:
   - vmn2

plan:
  stage: plan
  script: 
   - terraform plan -var-file="./env/terraform.tfvars" -out "configure.terraform"
  dependencies:
   - validate
  artifacts:
      paths:
        - configure.terraform
  tags:
    - vmn2

apply:
  stage: apply
  script:
    - terraform apply configure.terraform
  dependencies:
    - plan
  tags:
    - vmn2

deploy:
  stage: deploy
  script:
    - sudo service docker start
    - docker version
    - docker-compose --file ./docker-compose.yml up --detach
    #- docker-compose up --detach

  dependencies:
    - plan
  tags:
    - vmn2
