
stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - echo "Build"
  tags:
    - vmn2

test:
  stage: test
  script:
    - echo "Test"
  tags:
    - vmn2

deploy:
  stage: deploy
  script:
    - sudo service docker start
    - docker version
    - docker-compose --file ./docker-compose.yml up --detach
    #- docker-compose up --detach

  dependencies:
    - test
  tags:
    - vmn2
