
stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - echo "sudo service docker start"
    - echo "docker version"
    - echo "docker-compose --file ./docker-compose.yml up --detach"

  tags:
    - vmn2

test:
  stage: test
  script:
    - echo "test sudo service docker start"
    - echo "test docker version"
    - echo "test docker-compose --file ./docker-compose.yml up --detach"

  dependencies:
    - build
  tags:
    - vmn2

deploy:
  stage: deploy
  script:
    - sudo service docker start
    - docker version
    - docker-compose --file ./docker-compose.yml up --detach
    - echo "Deployment of containers DB mysql, CMS Wordpress, Proxy Server Nginx"


  dependencies:
    - test
  tags:
    - vmn2
