
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - sudo service docker start
    - docker version
    - docker-compose --file ./docker-compose.yml up --detach
    #- docker-compose up --detach

  #dependencies:
  #  - test
  tags:
    - vmn2
