cidr_block = "10.0.0.0/16"
profile = "final"
stage = "dev"
#ami = "ami-0b0ea68c435eb488d"
#instance_type = "t2.micro"
namespace = "nichiporenko"
#db_identifier = "vmnwordpress"
#dbname = "vmnwordpress"
#db_version = "5.7"
#pass = "vmnwordpress"
region = "us-east-1"  

access_key = "AKIAQ4YONN2MV2NQNTNY"
secret_key = "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"
